fivem:
  image: joebiellik/fivem

  stdin_open: true
  tty: true

  volumes:
    # You must provide a server config file
    - ./server.cfg:/srv/server.cfg

    - ./resources:/srv/resources
    - ./cache:/srv/cache

  ports:
    - "30120:30120/tcp"
    - "30120:30120/udp"

mysql:
  image: mysql:latest
  container_name: dev_mysql
  environment:
    MYSQL_USER: user
    MYSQL_PASSWORD: user
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: default_schema
  ports:
    - 3306:3306
  volumes:
    #- "./config/my.conf:/etc/mysql/conf.d/config-file.cnf"
    - "./sqldata:/var/lib/mysql:rw"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: dev_pma
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
    PMA_ARBITRARY: 1
  restart: always
  ports:
    - 8183:80